# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on: [push, pull_request]

jobs:

  unittests_legacy:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["2.7", "3.6"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install packages
        run: |
          sudo apt-get install swig softhsm2 opensc libengine-pkcs11-openssl

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
          python setup.py develop
          pip install nose

      - name: Test with nosetest
        run: |
          python setup.py test

  unittests:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install packages
        run: |
          sudo apt install swig softhsm2 opensc libengine-pkcs11-openssl

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
          pip install pytest

      - name: Test with pytest
        run: |
          make test

#  typecheck:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Set up Python 3.x
#        uses: actions/setup-python@v4
#        with:
#          python-version: 3.x
#
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r requirements/test_requirements.txt
#
#      - name: Run mypy to check types
#        run: |
#          mypy --version
#          make typecheck

